### ISSUE TITLE
Some problems to fix

### ISSUE THREAD

**Issue by AntoineJT** [raphaaell/HeadsOrTails#2]
## TODO

- [x] Remove binary files (build/, headsortails.jar)
Most of binaries should not be included in a git repository. Here, none of those already there should be included.

- [ ] Make use of a .gitignore (don't forget to add files to remove to it)
In order to disallow them to be commited, you should create a `.gitignore`.

- [x] Add headsortails.jar to the releases tab
You can, if you want, add headsortails.jar to the releases tab. Do not commit it.

- [x] Don't abbreviate variable names
Correctly name your variables: no more `nbrPS` or `pf` because no one except you understand what it means.

- [ ] Respect Java conventions (at least for variable naming)
- [ ] Give meaningful names to your variables

**Comment by AntoineJT** [comment]
`String[] HeadsTails = new String[]{"Heads", "Tails"};` : this variable should not be named using PascalCase but named using camelCase.
Its name is bad too, it should be called `side` or `coinSide`.
